/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.amil.conversorcsv.view;

import br.com.amil.conversorcsv.model.Relatorio;
import java.awt.BorderLayout;
import java.util.List;
import javax.swing.JScrollBar;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author fernando-pucci
 */
public class ListaDadosView extends javax.swing.JFrame {

    private List<Relatorio> relatorios;
    private String[] colunas;
    private DefaultTableModel modelo;
    private JScrollPane barraHorizontal;
    

    public ListaDadosView(List<Relatorio> relatorios) {

        this.relatorios = relatorios;
        this.colunas = Relatorio.FILE_HEADER_MAPPING;
        this.modelo = new DefaultTableModel();

        initComponents();

        iniciaTabela();
        
        jTableTabelaDados.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        this.barraHorizontal = new JScrollPane(jTableTabelaDados);
        this.barraHorizontal.setHorizontalScrollBar(new JScrollBar(0));
        
       

    }

    //construtor Privado
    private ListaDadosView() {
        //iniciaTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableTabelaDados = new javax.swing.JTable();
        jButtonFechar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Relatórios");
        setMaximumSize(new java.awt.Dimension(1024, 768));
        setMinimumSize(new java.awt.Dimension(1024, 768));
        setName("frameTabelaRelatorios"); // NOI18N
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1024, 768));
        setResizable(false);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setFocusTraversalPolicyProvider(true);

        jTableTabelaDados.setModel(modelo);
        jTableTabelaDados.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTableTabelaDados.setAutoscrolls(false);
        jTableTabelaDados.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTableTabelaDados);

        jButtonFechar.setText("Fechar");
        jButtonFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFecharActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jButtonFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(869, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(715, Short.MAX_VALUE)
                .addComponent(jButtonFechar)
                .addGap(23, 23, 23))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFecharActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonFecharActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListaDadosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListaDadosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListaDadosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListaDadosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListaDadosView().setVisible(true);
            }
        });
    }

    private void iniciaTabela() {

        jTableTabelaDados = new JTable(modelo);

        for (String s : colunas) {

            modelo.addColumn(s);

        }

        for (int i = 0; i < colunas.length; i++) {
            jTableTabelaDados.getColumnModel().getColumn(i).setPreferredWidth(1400);
        }

        modelo.setNumRows(0);

        for (Relatorio r : relatorios) {

            modelo.addRow(new Object[]{r.getCodigoPrestador(),
                r.getNomeOperadora(),
                r.getCodigoFilial(),
                r.getNomeFilial(),
                r.getRegiaoSaude(),
                r.getSubRegiaoSaude(),
                r.getCodigoUnidade(),
                r.getNomeUnidade(),
                r.getCodigoRede(),
                r.getNomeRede(),
                r.getTipoPessoa(),
                r.getCapituloOrientador(),
                r.getElementoDivulgacao(),
                r.getNomePrestador(),
                r.getTipoLogradouro(),
                r.getEnderecoPrestador(),
                r.getNumero(),
                r.getComplemento(),
                r.getMunicipio(),
                r.getBairro(),
                r.getCep(),
                r.getUf(),
                r.getDddTelefone1(),
                r.getTelefone1(),
                r.getDddTelefone2(),
                r.getTelefone2(),
                r.getDddFax(),
                r.getFax(),
                r.getDireciona(),
                r.getEmail(),
                r.getTipoEquipamento(),
                r.getIsComercializado(),
                r.getModeloOrientador(),
                r.getRedePropria(),
                r.getClassificacoes(), r.getA(), r.getB(), r.getC()
            });

        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonFechar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableTabelaDados;
    // End of variables declaration//GEN-END:variables
}
